### ISSUE TITLE
Poke Flute logic

### ISSUE THREAD

**Issue by Cybrou** [j-imbo/pkmnrb_jim#1]
Hello,

I think that there is a mistake with the Poke flute logic. Pokeflute allows you to acces to Route 12 from Route 11 but the tracker don't show it :

![image](https://user-images.githubusercontent.com/106977036/202594413-c467f51b-c69a-44ff-b528-08044b5d9e4e.png)

**Comment by j-imbo** [comment]
Fixed this a while ago, forgot to push changes... Thanks for the reminder
