### ISSUE TITLE
Save Mr. Fuji Autotracking

### ISSUE THREAD

**Issue by vicendithas** [j-imbo/pkmnrb_jim#7]
Overall the autotracking with Archipelago has been great, and the pack itself has been fantastic. I noticed, however, that the tracker didn't automatically mark the "7F Save Mr. Fuji" location in the Pokemon Tower or the "Fuji Save" item after completing the Pokemon Tower. Because of this, I didn't realize that Silph Co was actually available for a while.

**Comment by j-imbo** [comment]
Due to this being an event, it is impossible to autotrack accurately.
