### ISSUE TITLE
Pokedex Tracking

### ISSUE THREAD

**Issue by vicendithas** [j-imbo/pkmnrb_jim#8]
This is a very minor thing I noticed. I'm playing an Archipelago game and the tracker isn't automatically incrementing my Pokedex count when I catch a new Pokemon. I'm not playing Dexsanity (or whatever it's called), but it's would still be nice to keep track of for the Oak Aide checks.

**Comment by remyjette** [comment]
Right now this isn't possible without Dexsanity - the tracker only sees things that AP sees. Right now if Dexsanity isn't on then the client sends nothing when you get a pokedex entry.

This could potentially be resolved if the client sends non-item events to the tracker like emerald has done, but probably would best to do that for Fuji/Silph first before trying to tackling it for non-Dexsanity event checks

**Comment by silasary** [comment]
A side effect of this bug is that Oak's Aides are always red if you're not playing dexsanity

**Comment by j-imbo** [comment]
There is no simple or clean way to do this currently, if you want to track your dex progress, you must do it manually.
